pipeline {
  agent any

  environment {
    IMAGE_NAME = 'finance-tracker'
    IMAGE_TAG = 'latest'
    CONTAINER_NAME = 'finance-tracker-test'
    APP_PORT = '5000'
  }

  stages {
    stage('Clone Repo') {
      steps {
        git branch: 'main', url: 'https://github.com/Bhavik-1/finance-tracker.git'
      }
    }

    stage('Verify') {
      steps {
        sh 'ls -la'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -f docker/Dockerfile -t ${IMAGE_NAME}:${IMAGE_TAG} .'
      }
    }

    stage('Run Container') {
      steps {
        sh '''
          if [ "$(docker ps -aq -f name=^/${CONTAINER_NAME}$)" ]; then
            docker rm -f ${CONTAINER_NAME}
          fi

          docker run -d \
            --name ${CONTAINER_NAME} \
            -p ${APP_PORT}:5000 \
            ${IMAGE_NAME}:${IMAGE_TAG}

          docker ps
        '''
      }
    }
  }
}